### ISSUE TITLE
SDK location not found

### ISSUE THREAD

**Issue by goforgold** [mindrunner/docker-android-sdk#7]
I am getting this error during build on CircleCI (moving from Bitbucket pipelines)

I was using `uber/android-build-environment:latest` and the build was working fine as expected but CircleCI didn't support this image with some error.

Below is my build configuration on CircleCI

```
version: 2

jobs:
   build:
     docker:
       - image: runmymind/docker-android-sdk:latest
     steps:
       - checkout
       - run: echo ${ANDROID_HOME}
       - run: mkdir "${ANDROID_HOME}/licenses" || true && echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
       - run: ./gradlew assembleRelease
       - run: filename=app/build/outputs/apk/myApp-${BITBUCKET_BRANCH}-`date +"%Y-%m-%d-%H.%M.%S-%Z"`.apk && mv app/build/outputs/apk/app-release.apk ${filename}
       - run: curl -F file=@${filename} -F channels=#android-builds -F token=${SLACK_TOKEN} https://slack.com/api/files.upload
```

I am getting following error during build in CircleCI

`SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.`

Do we need to set environment variable as a step in build pipeline? What's the location where SDK is extracted?

Can someone help?

**Comment by mindrunner** [comment]
The Environment is defined in Dockerfile:

ENV ANDROID_SDK_HOME /opt/android-sdk-linux

Does that help you?

**Comment by goforgold** [comment]
Yeah, I found that but the command `./gradlew assembleRelease` is looking in `ANDROID_HOME` for this. I found a workaround for this by adding a custom env for this in CircleCI like below:

```
docker:
   - image: runmymind/docker-android-sdk:latest
     environment:
       ANDROID_HOME: /opt/android-sdk-linux
```

But I wish if you could set this by default so it would be convenient for other users.

Also, are you accepting license in image itself or do I need to accept them manually? I run command `mkdir "${ANDROID_HOME}/licenses" || true && echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"` for accepting license in `uber/android-build-environment:latest` but here with your image it reports that directory already exists. I am guessing that I can remove this step. Can I?

And one last thing, can you install Git and Curl into the image itself. I am having to include them manually in a build step, causing unnecessary build time. Or at least install `curl`.

Thank you.
